parameters:
#    petr_direct_api.example.class: Petr\DirectApiBundle\Example

services:
#    petr_direct_api.example:
#        class: %petr_direct_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
