parameters:
    direct_api.service.class: Petr\DirectApiBundle\Service\DirectService

services:
    direct:
        class: %direct_api.service.class%
        arguments: [@doctrine.orm.entity_manager, @kernel, @buzz]
