# Конфигурация для Яндекс.Директ API

sandbox_url: "https://api-sandbox.direct.yandex.ru/live/v4/json/"
usertoken: "15d86aaeb08d4db29a188cb7bb9db057"
locale: "ru"

# режим отладки запросов
debug: true
